package org.example.IR;

//minus - унарный минус
public enum Operator {
    minus, PLUS, MINUS, DIVIDE, MULTIPLY, AND, OR, IFFALSE, FOR, GOTO, ASSIGN, IFTRUE, LESS, MORE, NOT_EQUAL, LESS_EQUAL, GREATER_EQUAL, NOT, EQUAL, PARAM, CALL, END, RETURN, ID, PRINT, MODULO, INPUT
}
